# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dominic Gan
subtitle: >
  Web Designer &amp; Front-end Developer,<br>
  currently at <a href="https://www.mirumagency.com/singapore" target="_blank" rel="noopener" title="Mirum Agency">Mirum Agency</a>.
email: dominicgangx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey, I'm Dominic, a web designer and front-end developer based in Singapore!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dominicgan.github.io" # the base hostname & protocol for your site
build-info: Built with Jekyll, Gulp & Sass.
copyright: >
  &copy; 2018 Dominic Gan. All Rights Reserved.
# twitter_username: jekyllrb
github_username:  dominicgan

# Build settings
markdown: kramdown

# Exclusions
exclude: ["bower_components", "node_modules"]
#gems
# gems:
  # - jekyll-srcset

#jekyll-srcset settings
# srcset:
#   optipng: true
#   cache: "/tmp/images"
