# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dominic Gan
subtitle: >
  Web Designer &amp; Front-end Developer,<br>
  currently at <a href="http://www.group.ong-ong.com" target="_blank" name="ONG&ONG Group Pte Ltd">ONG&amp;ONG Pte Ltd</a>.
email: dominicgangx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey, I'm Dominic, and I am a web designer and front-end developer based in Singapore. I make websites and web apps!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dominicgan.github.io" # the base hostname & protocol for your site
build-info: Built with Jekyll, Gulp, Sass (and a whole bunch of mechanical keyboards and trackballs.)
copyright: >
  &copy; 2016 Dominic Gan. All Rights Reserved.
# twitter_username: jekyllrb
github_username:  dominicgan

# Build settings
markdown: kramdown

#gems
# gems:
  # - jekyll-srcset

#jekyll-srcset settings
# srcset:
#   optipng: true
#   cache: "/tmp/images"